default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      timeout: 5000
      username: <%= ENV['USERNAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: floot-test_development

test:
  <<: *default
  database: floot-test_test

production:
  database: <%= ENV['DATABASE_URL'] %>